version: '3.9'

services: 

  database:
    container_name: todo_database

    image: mongo

    ports: 
      - 27018:27017

    volumes: 
      - /data:/data/db

  backend:
    container_name: todo_backend

    build: 
      context: ./backend
      dockerfile: ./Dockerfile

    expose: 
      - ${BACKEND_PORT}

    environment: 
      BACKEND_PORT: ${BACKEND_PORT}

    ports: 
      - ${BACKEND_PORT}:${BACKEND_PORT}

    volumes: 
      - ./backend:/backend

    depends_on: 
      - database

    command: npm start

  frontend:
    container_name: todo_frontend

    build: 
      context: ./frontend
      dockerfile: ./Dockerfile

    environment: 
      - FRONTEND_PORT=${FRONTEND_PORT}

    expose: 
      - ${FRONTEND_PORT}

    ports: 
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

    volumes: 
      - ./frontend:/frontend

    links: 
      - backend

    command:  npm start
